compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs

packageExtensions:
  "daisyui@4.12.10":
    dependencies:                   
      "postcss": "*"           
  "@typescript-eslint/utils@7.14.1":
    dependencies:                   
      "typescript": "*"           
  "@typescript-eslint/typescript-estree@7.18.0":
    dependencies:                   
      "typescript": "*"